### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by immaria** [DryWolfi/MIPZ_1#1]
Add additional checks to the code below:

https://github.com/DryWolfi/MIPZ_1/blob/2609ab569e5948cc3177f62155f93493027530e5/MIPZ_1/Models/Country.cs#L46-L55

**Comment by DryWolfi** [comment]
Done
https://github.com/DryWolfi/MIPZ_1/blob/124b13723a17f05249b75a5c2527758c1175952c/MIPZ_1/Models/Country.cs#L48-L59
