### ISSUE TITLE
Introduce const for magic numbers

### ISSUE THREAD

**Issue by IanaKhitsko** [DryWolfi/MIPZ_1#2]
https://github.com/DryWolfi/MIPZ_1/blob/193a94e5cdd4ff784ae544452b3e129d4f739101/MIPZ_1/Models/City.cs#L22

**Comment by DryWolfi** [comment]
Fixed
        [public const int StartCoins = 1000000;](https://github.com/DryWolfi/MIPZ_1/blob/24f087623271ec66955f284a60882874d40dc948/MIPZ_1/Models/City.cs#L8)
