### ISSUE TITLE
Const again

### ISSUE THREAD

**Issue by IanaKhitsko** [DryWolfi/MIPZ_1#3]
https://github.com/DryWolfi/MIPZ_1/blob/193a94e5cdd4ff784ae544452b3e129d4f739101/MIPZ_1/Models/City.cs#L39

the same - add const

**Comment by DryWolfi** [comment]
Const is added
https://github.com/DryWolfi/MIPZ_1/blob/24f087623271ec66955f284a60882874d40dc948/MIPZ_1/Models/City.cs#L9
