### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by IanaKhitsko** [DryWolfi/MIPZ_1#4]
https://github.com/DryWolfi/MIPZ_1/blob/193a94e5cdd4ff784ae544452b3e129d4f739101/MIPZ_1/Models/Country.cs#L69

why do you put the argument to exception if you don't use it in catch ? You should either use it or remove

**Comment by DryWolfi** [comment]
Exeptions argument was removed
https://github.com/DryWolfi/MIPZ_1/blob/24f087623271ec66955f284a60882874d40dc948/MIPZ_1/Models/Country.cs#L39
