### ISSUE TITLE
Add consts for 10

### ISSUE THREAD

**Issue by IanaKhitsko** [DryWolfi/MIPZ_1#5]
https://github.com/DryWolfi/MIPZ_1/blob/193a94e5cdd4ff784ae544452b3e129d4f739101/MIPZ_1/Models/Country.cs#L48

In every place, because you use it several times.

**Comment by DryWolfi** [comment]
Added a new const
https://github.com/DryWolfi/MIPZ_1/blob/24f087623271ec66955f284a60882874d40dc948/MIPZ_1/Models/Country.cs#L8
